### ISSUE TITLE
Fix last page when including a tutorial

### ISSUE THREAD

**Issue by jarooda** [jarooda/family-100#5]
Because the tutorial start with 0, the array length will need to be adjusted

<img width="962" alt="Screenshot 2024-05-30 at 21 23 00" src="https://github.com/jarooda/family-100/assets/71919479/66f00201-4362-420c-8d5a-224531457db9">

**Comment by danangace** [comment]
what is the expected behaviour, when user at the last question?

throw user to first question ? homepage? or thankyou page?


@jarooda

**Comment by danangace** [comment]
it should be modified `totalQuestion` ?
`const totalQuestion = Object.keys(questions).length - 1`

**Comment by jarooda** [comment]
> it should be modified `totalQuestion` ?
> `const totalQuestion = Object.keys(questions).length - 1`

yes i think that is the code that lead to a bug, should check if the question started with tutorial or not

**Comment by here-bossnanda** [comment]
need review yaa @jarooda on my PR https://github.com/jarooda/family-100/pull/7 to solve this issue
